name: Android Release

# 1
on:
  # 2
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # 3
  workflow_dispatch:

# 4
jobs:
  # 5
  build:
    # 6
    runs-on: ubuntu-latest

    # 7
    steps:
      # 8
      - uses: actions/checkout@v3
      # 9
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
      # 10
      - uses: subosito/flutter-action@v2
        with:
          # 11
          flutter-version: "3.0.0"
          channel: 'stable'
      # 12
      - name: Get dependencies
        run: flutter pub get

      # Runs a set of commands using the runners shell
      - name: Start release build
        run: flutter build appbundle
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}




#name: Build and Release
#
#on:
#  pull_request:
#    branches:
#      - master
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    name: Build and Release
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up Java
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: 12.x
#
#      - name: Set up Flutter
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: 3.x # Adjust the Flutter version as needed
#
#      - name: Install dependencies
#        run: flutter pub get
#
#      - name: Run tests
#        run: flutter test
#
#      - name: Build APKs
#        run: flutter build apk --debug --split-per-abi
#
#      - name: Push to Release
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: |
#            build/app/outputs/apk/debug/* # Only include Android artifacts
#          tag: v1.0.${{ github.run_number }}
#          token: ${{ secrets.TOKEN }}
